before_install:
- sudo apt-get -qq update
- sudo apt-get install npm
- sudo npm install newman --global;
jdk:
- oraclejdk8
language: java
script:
- touch /tmp/NOW
- echo GIBSTUDYSTART $(date)
- mvn clean install -Pfull
- echo GIBSTUDYEND $(date)
- cd $TRAVIS_BUILD_DIR
- echo TESTNUM $(find . -name TEST-*.xml -newer /tmp/NOW | wc -l)
services:
- docker
sudo: false
